version: "3"
services:
  web:
    build: 
      context: .
    depends_on:
      - mongodb
    ports:
      - 80:80
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_HOST=mongodb
      - MONGO_DB=firstmongo 
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
