version: "3"
services:
  web:
    build: .
    depends_on:
      - mongodb
    ports:
      - "80:80"
    links:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_DB: firstmongo
      DATABASE_CONNECTIONSTRING: mongodb://mongodb:27017/firstmongo
  mongodb:
    image: mongo:latest
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
